Repository CODAIT/pardata, pull requests merged in 2020-12, with the labels that each got.

#36 README: URL ibm -> codait
  README.md
  docs/source/user_guide/install.rst
Labels: bug, documentation

#59 Add note on why bandit is pinned to prev version
  requirements/lint.txt
Labels: test

#61 Dependabot should only label its PRs "dependabot"
  .github/dependabot.yml
Labels: test

#66 Correct formatting in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#89 Add a note to remove the workaround for a pandas bug
  pydax/loaders/_table.py
Labels: loader
