Repository CODAIT/pardata, pull requests merged in 2021-01, with the labels that each got.

#131 Upload built docs as artifacts
  .github/workflows/docs.yml
  tox.ini
Labels: CI, documentation

#112 Shutdown httpd before destructing HTTPServer objects
  tests/conftest.py
Labels: bug, test

#136 Update renovate file match pattern to include all requirements*.txt
  .github/renovate.json5
Labels: CI

#139 Renovate bot: Only group patches together, not minor
  .github/renovate.json5
Labels: CI

#145 Add more PyPI classifiers
  setup.py
Labels: documentation

#167 Lots of little docs cleanup after one pass
  docs/source/conf.py
  pydax/__init__.py
  pydax/_config.py
  pydax/_dataset.py
  pydax/_high_level.py
  pydax/_lock.py
  pydax/_schema.py
  pydax/_typing.py
  pydax/dataset.py
  pydax/exceptions.py
  pydax/loaders/__init__.py
  pydax/loaders/_base.py
  pydax/loaders/_format_loader_map.py
  pydax/loaders/_table.py
  pydax/loaders/_text.py
  pydax/loaders/table.py
  pydax/loaders/text.py
  pydax/schema.py
Labels: documentation

#166 Cleanup README a little bit
  README.md
Labels: documentation

#169 Add notebook showcasing DAX dataset
  docs/notebooks/pydax-debater-claim-demo.ipynb
Labels: documentation

#171 Renovate label shouldn't have any dashes
  .github/renovate.json5
Labels: CI

#175 Some aesthetic document improvements and cleanup
  docs/source/conf.py
  pydax/_dataset.py
  pydax/_high_level.py
Labels: documentation, enhancement

#188 Update the distributor figure
  docs/source/_static/intro-distributor.odg
  docs/source/_static/intro-distributor.svg
Labels: documentation
